import requests
from bs4 import BeautifulSoup
from textblob import TextBlob
url = 'https://en.wikipedia.org/wiki/Mullaperiyar_Dam'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

text = ' '.join([p.text for p in soup.find_all('p')])
print(text)

blob=TextBlob(text)
sentiment = blob.sentiment.polarity
print('Sentiment analysis of the given text is : ',sentiment)

"""
Output
---------
 Mullaperiyar Dam (IPA: [mulːɐpːeɾijɐːr]) is a masonry gravity dam on the Periyar River of Idukki district of Indian state of Kerala. It is situated 150km south east of Kochi and 200km north east of state capital city of Trivandrum.[2][3] It is located 881 m (2,890 ft) above the sea level, on the Cardamom Hills of the Western Ghats in Thekkady, Idukki District of Kerala, India. It was constructed between 1887 and 1895 by John Pennycuick and also reached in an agreement to divert water eastwards to the Madras Presidency area (present-day Tamil Nadu).[7] On 21 November 2014, the water level hit 142 feet for first time in 35 years.[8]
 The Periyar Lease Agreement between the Kingdom of Travancore and the British Government of India was signed in 1886. This agreement leased 8,100 acres of land and all the water flowing into it to the Madras Presidency under the British Government for 999 years at a rate of 5 British rupees per acre.[9]
 After India's independence, there was an opportunity to revoke or revise pre-independence agreements. However, the state government of Kerala at the time under C. Achutha Menon approved the Periyar lease deed on May 29, 1970,allegedly under pressure from the Prime Minister Indira Gandhi of the Congress Party to influence Tamil Nadu politics. The lease retaining most of the provisions of the 1886 agreement, including the 999-year tenure for Tamil Nadu. This decision later became a significant legal obstacle for the Kerala state.[10]
 Previously, Sir CP Ramaswamy Iyer had obtained an order stating that Tamil Nadu had no right to use water from Mullaperiyar for power generation. Despite this, the 1970 agreement granted Tamil Nadu the right to generate electricity from this water. Today Tamil Nadu uses the dam water for electricity generation. All of the water and electricity from the dam is used by Tamil Nadu,  while Kerala receives zero benefit from the dam, even though it is located in Kerala.[11] Tamil Nadu gets a revenue of about Rs 371 crore through agriculture and Rs 211 crore from power generation per year using Mullaperiyar water. In addition to Mullaperiyar, there are 8 dams in Kerala constructed for Tamil Nadu's needs, and not a single drop of water from these dams is available for Kerala's needs.[12][13]
 It has a height of 53.6 m (176 ft) from the foundation, and a length of 365.7 m (1,200 ft).[2] The Periyar National Park in Thekkady is located around the dam's reservoir. The dam is built at the confluence of Mullayar and Periyar rivers. The dam is located in Kerala on the river Periyar,[2][14] but is operated and maintained by the neighbouring state of Tamil Nadu.[2][15][16] Although the Periyar River has a total catchment area of 5398 km2 with 114 km2 downstream from the dam in Tamil Nadu,[17][18] the catchment area of the Mullaperiyar Dam itself lies entirely in Kerala and thus not an inter-State river.[19][20][7] On 21 November 2014, the water level hit 142 feet for first time in 35 years.[8] The reservoir again hit the maximum limit of 142 feet on 15 August 2018, following incessant rains in the state of Kerala. In a 2021 UNU-INWEH report about ageing large dams around the world, Mullaperiyar was said to be "situated in a seismically active area with significant structural flaws and poses risk to 3.5 million people if the 100+ years old dam were to fail".[21][22]
 Earlier known as the Periyar Dam as it was basically meant to dam the Periyar river,[23] the present name Mullaperiyar is derived by blending the names of Mullayar River and Periyar River, at the confluence of which the dam is located below.[24]
 The Periyar river which flows westward of Kerala in to the Arabian Sea was diverted eastwards to flow towards the Bay of Bengal to provide water to the arid rain shadow region of Madurai in Madras Presidency which was in dire need of a greater supply of water than the small Vaigai River could provide.[23] The dam created the Periyar Thekkady reservoir, from which water was diverted eastwards via a tunnel to augment the small flow of the Vaigai River. The Vaigai was dammed by the Vaigai Dam to provide a source for irrigating large tracts around Theni, Dindigul, Madurai, Sivagangai, Ramanathapuram districts. Initially the dam waters were used only for the irrigation of 68,558 ha (169,411 acres).[25]
 Currently, the water from the Periyar (Thekkady) Lake created by the dam, is diverted through the water shed cutting and a tunnel to Forebay Dam near Kumily (Iraichalpalam). From the Forebay dam, hydel pipelines carry the water to the Periyar Power Station in Lower Periyaru. This is used for power generation (180 MW capacity) in the Periyar Power Station.[26][27][28] From the Periyar Power Station, the water is let out into Vairavanar river and then to Suruliyar and from Suruliyar to Vaigai Dam.[29]
 The Mullaperiyar Dam is a gravity dam made with concrete prepared from limestone and "surkhi" (burnt brick powder), and faced with rubble.[30] Gravity dams use their weight and the force of gravity to support the reservoir and remain stable.[3][31] The main dam has a maximum height of 53.6 m (176 ft) and length of 365.7 m (1,200 ft). Its crest is 3.6 m (12 ft) wide while the base has a width of 42.2 m (138 ft). It consists of a main dam, spillway on its left and an auxiliary dam (or "baby dam") to the right. Its reservoir can withhold 443,230,000 m3 (359,332 acre⋅ft) of water, of which 299,130,000 m3 (242,509 acre⋅ft) is active (live) storage.[3][5]
 The unique idea of harnessing the westward flowing water of the Periyar river and diverting it to the eastward flowing Vaigai river was first explored in 1789 by Pradani Muthirulappa Pillai, a minister of the Ramnad king Muthuramalinga Sethupathy, who gave it up as he found it to be expensive.[32] The location of the dam had first been scouted by Captain J. L. Caldwell, Madras Engineers (abbreviated as M.E.) in 1808 to reconnoitre the feasibility of providing water from the Periyar river to Madurai by a tunnel through the mountains. Caldwell discovered that the excavation needed would be in excess of 100 feet in depth and the project was abandoned with the comment in his report as "decidedly chimerical and unworthy of any further regard".[23]
 The first attempt at damming the Periyaar with an earthen dam in 1850 was given up due to demands for higher wages by the labour citing unhealthy living conditions.[31] The proposal was resubmitted a number of times and in 1862, Captain J. G. Ryves, M.E., carried out a study and submitted proposals in 1867 for another earthwork dam, 62 feet high. The matter was debated by the Madras Government and the matter further delayed by the terrible famine of 1876–77. Finally, in 1882, the construction of the dam was approved and Major John Pennycuick, M.E., placed in charge to prepare a revised project and estimate which was approved in 1884 by his superiors.[23]
 On 29 October 1886, a lease indenture for 999 years was made between the Maharaja of Travancore Moolam Thirunal Rama Varma, and the British Secretary of State for India for Periyar Irrigation Works. The lease agreement was signed by Dewan of Travancore V Ram Iyengar and State Secretary of Madras State J C Hannington. This lease was made after 24 years negotiation between the Maharaja and the British. The lease indenture granted full right, power and liberty to the Secretary of State for India to construct make and carry out on the leased land and to use exclusively when constructed, made and carried out, all such irrigation works and other works ancillary thereto. The agreement gave 8000 acres of land for the reservoir and another 100 acres to construct the dam. The tax for each acre was ₹ 5 per year. The lease provided the British the rights over "all the waters" of the Mullaperiyar and its catchment basin, for an annual rent of ₹ 40,000.[33]
 In 1947, after Indian Independence, Travancore and Cochin joined the Union of India and on 1 July 1949 were merged to form Travancore-Cochin. On 1 January 1950, Travancore-Cochin was recognised as a state. The Madras Presidency was organised to form Madras State in 1947. On 1 November 1956, the state of Kerala was formed by the States Reorganisation Act. The Kerala state government announced that the earlier agreement which had been signed between British Raj and Travancore agreement was invalid and needed to be renewed.[34]
 After several failed attempts to renew the agreement in 1958, 1960, and 1969, the agreement was renewed in 1970 when C Achutha Menon was Kerala Chief Minister. According to the renewed agreement, the tax per acre was increased to ₹ 30, and for the electricity generated in Lower Camp using Mullaperiyar water, the charge was ₹ 12 per kiloWatt per hour. Tamil Nadu uses the water and the land, and the Tamil Nadu government has been paying to the Kerala government for the past 50 years ₹ 2.5 lakhs as tax per year for the whole land and ₹ 7.5 lakhs per year as surcharge for the total amount of electricity generated.[33][35] The validity of this agreement is under dispute between the States of Kerala and Tamil Nadu. As of 2013 the matter is pending before a Division Bench of the Supreme Court.[36][37][38][39] The dispute puts into question the power of the federal government of India to make valid orders respecting Indian States, in this case regarding a watershed and dam within one state that is used exclusively in another.[40]
 In May 1887, construction of the dam began.[24][35] As per "The Military Engineer in India" Vol II by Sandes (1935), the dam was constructed from limestone and "surkhi" (burnt brick powder and a mixture of sugar and calcium oxide )[31] at a cost of ₹ 104 lakhs, was 173 feet high and 1241 feet in length along the top and enclosed more than 15 thousand million cubic feet of water.[23] Another source states that the dam was constructed of concrete and gives a figure of 152 feet height of the full water level of the reservoir, with impounding capacity of 10.56 thousand million cubic feet along with a total estimated cost of ₹ 84.71 lakh.[23]
 The construction involved the use of troops from the 1st and 4th battalions of the Madras Pioneers as well as Portuguese carpenters from Cochin who were employed in the construction of the coffer-dams and other structures.[23] The greatest challenge was the diversion of the river so that lower portions of the great dam could be built. The temporary embankments and coffer-dams used to restrain the river waters were regularly swept away by floods and rains. Due to the coffer dam failures, the British stopped funding the project. Officer Pennycuick raised funds by selling his wife's jewelry to continue the work.[32] In Madurai, Pennycuick's statue has been installed at the state PWD office and his photographs are found adorning walls in peoples homes and shops. In 2002, his great-grandson was honoured in Madurai, a function that was attended by thousands of people.[32]
 The dam created a reservoir in a remote gorge of the Periyar river situated 3,000 feet above the sea in dense and malarial jungle, and from the northerly arm of this manmade waterbody, the water flowed first through a deep cutting for about a mile and then through a tunnel, 5704 feet in length and later through another cutting on the other side of the watershed and into a natural ravine and so onto the Vaigai River which has been partly built up for a length of 86 miles, finally discharging 2000 cusecs of water for the arid rain shadow regions of present-day Theni, Dindigul District, Madurai District, Sivaganga District and Ramanathapuram districts of Tamil Nadu, then under British rule as part of Madras Province (Sandes, 1935).[23]
 The Periyar project, as it was then known, was widely considered well into the 20th century as "one of the most extraordinary feats of engineering ever performed by man".[23] A large amount of manual labour was involved and worker mortality from malaria was high. It was claimed that had it not been for "the medicinal effects of the native spirit called arrack, the dam might never have been finished".[23] 483 people died of diseases during the construction of this dam and were buried on-site in a cemetery just north of the dam.
 In 2012, it was announced that a memorial dedicated to dam engineer Pennycuick would be erected at the dam site.[41]
 The Periyar National Park in Thekkady, a Protected area of Kerala, is located around the dam's reservoir, the 26 km2 (10 sq mi) Periyar lake. 62 different kinds of mammals have been recorded in Periyar, including many threatened ones. Periyar is a highly protected tiger reserve and hosts 35 tigers above two-years of age as of January 2017 in the reserve.[42][43] Declared an elephant reserve on 2 April 2002,[44] the population of Indian elephants in 2005 was estimated at 1100,[44] however Periyar suffers greatly from poaching of elephant being the worst affected of South Indian sanctuaries.[45]
 Other mammals found here include gaur, bison, sambar (horse deer), barking deer, mouse deer, dholes (Indian wild dogs), mongoose, foxes and leopards. Four species of primates are found at Periyar – the rare lion-tailed macaque, the Nilgiri langur, the common langur, and the bonnet macaque. According to a report by the Kerala Forest Research Institute, the protected area surrounding the dam and reservoir is classified as a biodiversity hot spot.[46]
 After the 1979 Morvi Dam failure which killed up to 15,000 people,[47] safety concerns of the aging Mullaperiyar dam and alleged leaks and cracks in the structure were raised by the Kerala Government.[48] A study conducted by The Centre for Earth Science Studies (CESS), Thiruvananthapuram, had reported that the structure would not withstand an earthquake above magnitude 6 on the Richter scale.[48] The dam was also inspected by the chairman, CWC (Central Water Commission). On the orders of the CWC, the Tamil Nadu government lowered the storage level from 152 feet to 142.2 feet then to 136 feet, conducted safety repairs and strengthened the dam.[25]
 Strengthening measures adopted by Tamil Nadu PWD from 1979 with the recommendation of Central Water Commission(CWC) include grouting of the old dam with concrete, guniting the upstream face of dam, cable anchoring of the dam's structure with the foundation throughout its length, RCC(Reinforced Concrete Construction) capping on top of the dam at height above 145 feet, building 10 meter RCC concrete backing structure with 10 feet foundation up to height of 145 feet in downstream face of dam and binding the RCC structure using shear keys and concrete grouting with the old structure and the foundation along the downstream face of dam, building additional drainage galleries in order to measure seepage and additional sluice gates for water evacuation.[49][50]
 During a 2011 scanning of the Mullaperiyar dam using a remotely operated vehicle by the Central Soil and Materials Research Station on directions from the Empowered Committee of the Supreme Court, the Kerala Government observer opined that "mistakes in the strengthening works carried out by Tamil Nadu" in 1979 damaged the masonry of the dam.[51]
 Current safety concerns relate to several issues. Since the dam was constructed using stone rubble masonry with lime mortar grouting following prevailing 19th-century construction techniques that have now become archaic, seepage and leaks from the dam have caused concern.[52][53] Moreover, the dam is situated in a seismically active zone.[54] An earthquake measuring 4.5 on the Richter scale occurred on 7 June 1988 within 20 km of the dam.[55] Subsequently, several tremors have occurred in the area in recent times. These could be reservoir-induced seismicity, requiring further studies according to experts.[56]  A 2009 report by IIT Roorkee stated that the dam "was likely to face damage if an earthquake of the magnitude of 6.5 on the Richter scale struck its vicinity when the water level is at 136 feet".[57]
 On 18 February 2010, the Supreme Court decided to constitute a five-member empowered committee consisting three judges and two technical experts to inspect and study all the issues of Mullaperiyar Dam and seek a report from it within six months.[58] The Bench in its draft order said Tamil Nadu and Kerala would have the option to nominate a member each, who could be either a retired judge or a technical expert. The five-member committee will be headed by former Chief Justice of India A. S. Anand to go into all issues relating to the dam's safety and the storage level.
 The then late Tamil Nadu Chief Minister M. Karunanidhi said that immediately after the Supreme Court announced its decision to set up a committee, he had written to Congress president asking the centre to mediate between Kerala and Tamil Nadu on Mullaperiyar issue.[59] However, the then Leader of Opposition i.e., the late Chief Minister of Tamil Nadu J. Jayalalithaa objected to the TN Government move. She said that this would give advantage to Kerala in the issue.[60] Meanwhile, Kerala Water Resources Minister N. K. Premachandran told the state Assembly that the State should have the right of construction, ownership, operation and maintenance of the new dam, while giving water to Tamil Nadu on the basis of a clear cut agreement. He also informed the media that former Supreme Court Judge K. T. Thomas will represent Kerala on the expert panel constituted by Supreme Court.[61]
 On 8 March 2010, Tamil Nadu told the Supreme Court that it was not interested in adjudicating the dispute with Kerala before the special "empowered" committee appointed by the apex court for settling the inter-State issue.[62] However, Supreme Court refused to accept Tamil Nadu's request to scrap the decision to form the empowered committee. The Supreme Court also criticized the Union Government on its reluctance in funding the empowered committee.[63]
 The Empowered Committee headed by the former Chief Justice of India A.S. Anand, in its findings concluded that the dam is "structurally, hydrologically safe, and Tamil Nadu can raise the water level from 136 to 142 feet after carrying out repairs."[64]
 The control and safety of the dam and the validity and fairness of the lease agreement have been points of dispute between Kerala and Tamil Nadu states.[65]
Supreme court judgment came on 27 February 2006, allowing Tamil Nadu to raise the level of the dam to 152 ft (46 m) after strengthening it. Responding to it, Mullaperiyar dam was declared an 'endangered' scheduled dam by the Kerala Government under the disputed Kerala Irrigation and Water Conservation (Amendment) Act, 2006.[66]
 Tamil Nadu has insisted on raising the water level in the dam to 142 feet, pointing out crop failures. However, the court has clarified Tamil Nadu is not a riparian state. "In the process the farmers of the erstwhile rain shadow areas in Tamil Nadu who had started a thrice yearly cropping pattern had to go back to the bi-annual cropping."[67]
 The Kerala Government maintains that this is not true. During the year 1979–80 the gross area cultivated in Periyar command area was 171,307 acres (693.25 km2). After the lowering of the level to 136 ft (41 m), the gross irrigated area increased and in 1994–95 it reached 229,718 acres (929.64 km2).[68]
 In 2006, the Supreme Court of India by its decision by a three-member division bench, allowed for the storage level to be raised to 142 feet (43 m) pending completion of the proposed strengthening measures, provision of other additional vents and implementation of other suggestions.
 However, the Kerala Government promulgated a new "Dam Safety Act" against increasing the storage level of the dam, which has been challenged by Tamil Nadu on various grounds. The Supreme Court issued notice to Kerala to respond, however did not stay the operation of the Act even as an interim measure. The Court then advised the States to settle the matter amicably, and adjourned hearing in order to enable them to do so. The Supreme Court of India termed the act as not unconstitutional.[69] Meanwhile, the Supreme Court constituted a Constitution bench to hear the case considering its wide ramifications.[25]
 The Kerala Government states that it does not object to giving water to Tamil Nadu as a shared commodity, their main cause of objection being the dam's safety as it is 126 years old. Increasing the level would add more pressure to be handled by the already leaking dam. They also raised the problematic definition of inter-State river when in its entirety the river goes into the sea within Kerala without passing through any other states. They also raised the complexity of the judgment and disputes that it can raise in other states that have small catchments of other-State rivers and right to claim part of waters.[70]
 In May 2014 the Supreme Court of India declared the Kerala Irrigation and Water Conservation (Amendment) Act of 2006 as unconstitutional and struck down the law passed by the Kerala Assembly on the Mullaperiyar Dam that said that the water level cannot be increased beyond 136 feet.[71] The court has ruled that Tamil Nadu can increase the water level to 142 feet and constituted a permanent Supervisory Committee in order to take care of the affairs relating to maintenance of the Mullaperiyar Dam.[72]
 In 2014 while passing the final verdict, the Supreme Court constituted a permanent Supervisory Committee to oversee all the aspects of the Mullaperiyar dam. The Supervisory Committee consists of three members headed by member from the Central Water Commission of The Water Resource Ministry who will act as the chairman of the Supervisory Committee and two other members from the respective states.[73]
 To assist the three member supervisory committee, a five-member sub-supervisory committee was formed comprising two officials from both the respective States and a member from the Central Water Commission acting as the head.[74]
 In 2014 while passing the final judgement the Supreme Court has laid down criteria for any future construction of new dam downstream and decommissioning of the present Mullaperiyar Dam under the "Way Forward - Towards an amicable solution" or a tunnel solution as suggested by the Empowered Committee (EC).[75][76] The second tunnel can bring down the water level considerably in the dam and it is as good as decommissioning the dam without hindering supply of water to Tamil Nadu.[77]
 The judgement emphasized the suggestion of EC to make a second tunnel at about 50 ft from the bottom so that the large quantity of water, otherwise unused below the current tunnel at 106.5 ft, can be used by Tamil Nadu. It was highlighted that in case the dam develops any distress, this tunnel will help in evacuation of storage faster and better. It was also pointed out that the costs will be meagre compared to building a new dam.[78]
 The safety of the dam again rose to public attention in 2021 after the flood situation in Kerala since 2018 and the destruction of Rishiganga hydroelectric project & Tapovan dam in Uttarakhand following a glacier burst killing nearly 200 people.[79] A UNU-INWEH report on threats possessed by ageing dams across the world stated that Mullaperiyar dam situated in a seismically active area has major structural flaws and 3.5 million people are at risk if the 100+ years old dam were to fail.[80][21][22] 2 petitions were filed in Supreme Court alleging that the supervisory committee formed as per Supreme Court order in 2014 was not functioning properly for the past 6 years, responding to which the Supreme Court ordered Chief Secretary of Tamil Nadu to come out with the rule curve immediately or face action.[81] The Supreme Court, which declared the dam as hydrologically and seismically safe previously in 2014, asked Kerala and Tamil Nadu states to act seriously as 'people's lives are at risk' in a U turn.[82][83]
 Tension rose again when Tamil Nadu opened 10 shutters of the dam after midnight without giving proper warning, causing floods along the banks of the Periyar River. It was the 4th time in a month that Tamil Nadu has opened the shutters of the dam after 10 pm. This resulted in Chief Minister of Kerala, Pinarayi Vijayan sending a letter to his Tamil Nadu counterpart to open shutters of dam only at daytime that too with proper warnings.[84][85]

Sentiment analysis of the given text is :  0.037113683418031236

"""



